version: "3.8"

services:
  frontend:
    build:
      context: ./
      dockerfile: packages/frontend/Dockerfile
    ports:
      - "${FRONTEND_PORT}:80"
    env_file:
      - .env

  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    ports:
      - "${BACKEND_PORT}:4000"
    env_file:
      - .env
