version: '3.8'

services:
  frontend:
    build:
      context: ./
      dockerfile: packages/frontend/Dockerfile
    ports:
      - '${FRONTEND_PORT}:80'
    env_file:
      - .env

  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    ports:
      - '${BACKEND_PORT}:4000'
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - '${MONGO_PORT}:27017'
    command: ['--quiet']
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

volumes:
  mongo_data:
    driver: local
